/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.03.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * 
 * @param min_app_version Internal use - Minimum application version required to correctly connect and process data.
 * @param latest_app_version Internal use - Latest application version available.
 */
data class API_Status_App_Version (
    /* Internal use - Minimum application version required to correctly connect and process data. */
    val min_app_version: kotlin.Int,
    /* Internal use - Latest application version available. */
    val latest_app_version: kotlin.Int
) {

}

