/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.04.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * An `Award_Recipient` object represents the team and/or person who received an award at an event.
 * @param team_key The TBA team key for the team that was given the award. May be null.
 * @param awardee The name of the individual given the award. May be null.
 */
data class Award_Recipient (
    /* The TBA team key for the team that was given the award. May be null. */
    val team_key: kotlin.String? = null,
    /* The name of the individual given the award. May be null. */
    val awardee: kotlin.String? = null
) {

}

