/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.04.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models

import net.thefletcher.tbaapi.v3client.models.Award_Recipient

/**
 * 
 * @param name The name of the award as provided by FIRST. May vary for the same award type.
 * @param award_type Type of award given. See https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/award_type.py#L6
 * @param event_key The event_key of the event the award was won at.
 * @param recipient_list A list of recipients of the award at the event. Either team_key and/or awardee for individual awards.
 * @param year The year this award was won.
 */
data class Award (
    /* The name of the award as provided by FIRST. May vary for the same award type. */
    val name: kotlin.String,
    /* Type of award given. See https://github.com/the-blue-alliance/the-blue-alliance/blob/master/consts/award_type.py#L6 */
    val award_type: kotlin.Int,
    /* The event_key of the event the award was won at. */
    val event_key: kotlin.String,
    /* A list of recipients of the award at the event. Either team_key and/or awardee for individual awards. */
    val recipient_list: kotlin.Array<Award_Recipient>,
    /* The year this award was won. */
    val year: kotlin.Int
) {

}

