/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.04.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models

import net.thefletcher.tbaapi.v3client.models.District_Ranking_event_points

/**
 * Rank of a team in a district.
 * @param team_key TBA team key for the team.
 * @param rank Numerical rank of the team, 1 being top rank.
 * @param rookie_bonus Any points added to a team as a result of the rookie bonus.
 * @param point_total Total district points for the team.
 * @param event_points List of events that contributed to the point total for the team.
 */
data class District_Ranking (
    /* TBA team key for the team. */
    val team_key: kotlin.String,
    /* Numerical rank of the team, 1 being top rank. */
    val rank: kotlin.Int,
    /* Total district points for the team. */
    val point_total: kotlin.Int,
    /* Any points added to a team as a result of the rookie bonus. */
    val rookie_bonus: kotlin.Int? = null,
    /* List of events that contributed to the point total for the team. */
    val event_points: kotlin.Array<District_Ranking_event_points>? = null
) {

}

