/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.03.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * Backup team called in, may be null.
 * @param &#x60;out&#x60; Team key that was replaced by the backup team.
 * @param &#x60;in&#x60; Team key that was called in as the backup.
 */
data class Elimination_Alliance_backup (
    /* Team key that was replaced by the backup team. */
    val `out`: kotlin.String? = null,
    /* Team key that was called in as the backup. */
    val `in`: kotlin.String? = null
) {

}

