/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.03.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * 
 * @param alliance_points Points awarded for alliance selection
 * @param award_points Points awarded for event awards.
 * @param qual_points Points awarded for qualification match performance.
 * @param elim_points Points awarded for elimination match performance.
 * @param total Total points awarded at this event.
 */
data class Event_District_Points_points (
    /* Points awarded for alliance selection */
    val alliance_points: kotlin.Int,
    /* Points awarded for event awards. */
    val award_points: kotlin.Int,
    /* Points awarded for qualification match performance. */
    val qual_points: kotlin.Int,
    /* Points awarded for elimination match performance. */
    val elim_points: kotlin.Int,
    /* Total points awarded at this event. */
    val total: kotlin.Int
) {

}

