/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.03.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * The `Media` object contains a reference for most any media associated with a team or event on TBA.
 * @param key TBA identifier for this media.
 * @param type String type of the media element.
 * @param foreign_key The key used to identify this media on the media site.
 * @param details If required, a JSON dict of additional media information.
 * @param preferred True if the media is of high quality.
 */
data class Media (
    /* TBA identifier for this media. */
    val key: kotlin.String,
    /* String type of the media element. */
    val type: Media.Type,
    /* The key used to identify this media on the media site. */
    val foreign_key: kotlin.String? = null,
    /* If required, a JSON dict of additional media information. */
    val details: kotlin.Any? = null,
    /* True if the media is of high quality. */
    val preferred: kotlin.Boolean? = null
) {

    /**
    * String type of the media element.
    * Values: youtube,cdphotothread,imgur,facebookMinusprofile,youtubeMinuschannel,twitterMinusprofile,githubMinusprofile,instagramMinusprofile,periscopeMinusprofile,grabcad,instagramMinusimage,externalMinuslink,avatar
    */
    enum class Type(val value: kotlin.Any){
    
        youtube("youtube"),
    
        cdphotothread("cdphotothread"),
    
        imgur("imgur"),
    
        facebookMinusprofile("facebook-profile"),
    
        youtubeMinuschannel("youtube-channel"),
    
        twitterMinusprofile("twitter-profile"),
    
        githubMinusprofile("github-profile"),
    
        instagramMinusprofile("instagram-profile"),
    
        periscopeMinusprofile("periscope-profile"),
    
        grabcad("grabcad"),
    
        instagramMinusimage("instagram-image"),
    
        externalMinuslink("external-link"),
    
        avatar("avatar");
    
    }

}

