/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.04.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models


/**
 * Backup status, may be null.
 * @param &#x60;out&#x60; TBA key for the team replaced by the backup.
 * @param &#x60;in&#x60; TBA key for the backup team called in.
 */
data class Team_Event_Status_alliance_backup (
    /* TBA key for the team replaced by the backup. */
    val `out`: kotlin.String? = null,
    /* TBA key for the backup team called in. */
    val `in`: kotlin.String? = null
) {

}

