/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* OpenAPI spec version: 3.03.1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package net.thefletcher.tbaapi.v3client.models

import net.thefletcher.tbaapi.v3client.models.WLT_Record

/**
 * 
 * @param dq Number of matches the team was disqualified for.
 * @param matches_played Number of matches played.
 * @param qual_average For some years, average qualification score. Can be null.
 * @param rank Relative rank of this team.
 * @param record 
 * @param sort_orders Ordered list of values used to determine the rank. See the `sort_order_info` property for the name of each value.
 * @param team_key TBA team key for this rank.
 */
data class Team_Event_Status_rank_ranking (
    /* Number of matches the team was disqualified for. */
    val dq: kotlin.Int? = null,
    /* Number of matches played. */
    val matches_played: kotlin.Int? = null,
    /* For some years, average qualification score. Can be null. */
    val qual_average: kotlin.Double? = null,
    /* Relative rank of this team. */
    val rank: kotlin.Int? = null,
    val record: WLT_Record? = null,
    /* Ordered list of values used to determine the rank. See the `sort_order_info` property for the name of each value. */
    val sort_orders: kotlin.Array<java.math.BigDecimal>? = null,
    /* TBA team key for this rank. */
    val team_key: kotlin.String? = null
) {

}

